require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] = podfile_properties['newArchEnabled'] == 'true' ? '1' : '0'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']

platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'
install! 'cocoapods',
  :deterministic_uuids => false

prepare_react_native_project!

target 'AI' do
  use_expo_modules!

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'node',
      '--no-warnings',
      '--eval',
      'require(require.resolve(\'expo-modules-autolinking\', { paths: [require.resolve(\'expo/package.json\')] }))(process.argv.slice(1))',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => podfile_properties['apple.ccacheEnabled'] == 'true',
    )
    fmt_header = File.join(__dir__, 'Pods', 'fmt', 'include', 'fmt', 'base.h')
    if File.exist?(fmt_header)
      contents = File.read(fmt_header)
      marker = '#if !defined(__cpp_lib_is_constant_evaluated)'
      unless contents.include?('#ifdef FMT_USE_CONSTEVAL')
        contents = contents.sub(
          marker,
          "#ifdef FMT_USE_CONSTEVAL\n#elif !defined(__cpp_lib_is_constant_evaluated)"
        )
        File.write(fmt_header, contents)
      end
    end

    fmt_inl = File.join(__dir__, 'Pods', 'fmt', 'include', 'fmt', 'format-inl.h')
    if File.exist?(fmt_inl)
      contents = File.read(fmt_inl)
      replacements = {
        'fmt::format_to(it, FMT_STRING("{}{}"), message, SEP);' =>
          'fmt::format_to(it, "{}{}", message, SEP);',
        'fmt::format_to(it, FMT_STRING("{}{}"), ERROR_STR, error_code);' =>
          'fmt::format_to(it, "{}{}", ERROR_STR, error_code);',
        'out = fmt::format_to(out, FMT_STRING("{:x}"), value);' =>
          'out = fmt::format_to(out, "{:x}", value);',
        'out = fmt::format_to(out, FMT_STRING("{:08x}"), value);' =>
          'out = fmt::format_to(out, "{:08x}", value);',
        'out = fmt::format_to(out, FMT_STRING("p{}"),' =>
          'out = fmt::format_to(out, "p{}",'
      }
      replacements.each do |before, after|
        contents = contents.gsub(before, after)
      end
      File.write(fmt_inl, contents)
    end

    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
end
