DROP POLICY IF EXISTS users_self_select ON public.users;
DROP POLICY IF EXISTS users_self_update ON public.users;
DROP POLICY IF EXISTS pregnancy_profiles_owner_access ON public.pregnancy_profiles;
DROP POLICY IF EXISTS chat_sessions_owner_access ON public.chat_sessions;
DROP POLICY IF EXISTS chat_messages_owner_access ON public.chat_messages;
DROP POLICY IF EXISTS emotion_logs_owner_access ON public.emotion_logs;
DROP POLICY IF EXISTS calendar_logs_owner_access ON public.calendar_logs;
DROP POLICY IF EXISTS knowledge_items_published_select ON public.knowledge_items;
DROP POLICY IF EXISTS knowledge_items_admin_write ON public.knowledge_items;
DROP POLICY IF EXISTS message_links_owner_select ON public.message_links;
DROP POLICY IF EXISTS message_links_admin_write ON public.message_links;
DROP POLICY IF EXISTS pregnancy_documents_admin_select ON public.pregnancy_documents;
DROP POLICY IF EXISTS pregnancy_documents_admin_write ON public.pregnancy_documents;
DROP POLICY IF EXISTS admin_audit_logs_admin_access ON public.admin_audit_logs;
DROP POLICY IF EXISTS user_action_logs_user_select ON public.user_action_logs;
DROP POLICY IF EXISTS user_action_logs_user_insert ON public.user_action_logs;
DROP POLICY IF EXISTS user_action_logs_admin_access ON public.user_action_logs;
DROP POLICY IF EXISTS pregnancy_weeks_public_select ON public.pregnancy_weeks;
DROP POLICY IF EXISTS pregnancy_weeks_admin_write ON public.pregnancy_weeks;
DROP POLICY IF EXISTS pregnancy_week_sections_public_select ON public.pregnancy_week_sections;
DROP POLICY IF EXISTS pregnancy_week_sections_admin_write ON public.pregnancy_week_sections;
DROP POLICY IF EXISTS pregnancy_week_assets_public_select ON public.pregnancy_week_assets;
DROP POLICY IF EXISTS pregnancy_week_assets_admin_write ON public.pregnancy_week_assets;

ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.pregnancy_profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.emotion_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.calendar_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.knowledge_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.message_links DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.pregnancy_documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_audit_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_action_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.pregnancy_weeks DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.pregnancy_week_sections DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.pregnancy_week_assets DISABLE ROW LEVEL SECURITY;

DROP TRIGGER IF EXISTS trg_users_updated_at ON public.users;
DROP TRIGGER IF EXISTS trg_pregnancy_profiles_updated_at ON public.pregnancy_profiles;
DROP TRIGGER IF EXISTS trg_chat_sessions_updated_at ON public.chat_sessions;
DROP TRIGGER IF EXISTS trg_knowledge_items_updated_at ON public.knowledge_items;
DROP TRIGGER IF EXISTS trg_chat_messages_touch_session ON public.chat_messages;
DROP TRIGGER IF EXISTS trg_pregnancy_weeks_updated_at ON public.pregnancy_weeks;

DROP FUNCTION IF EXISTS public.set_updated_at();
DROP FUNCTION IF EXISTS public.touch_chat_session_last_message();
DROP FUNCTION IF EXISTS public.is_admin_user();
